
import { Layout } from "../../Tools/Layout/Layout"

export const Terms = () => {
    return (
        <>
            <Layout title="Salgs og handelsbetingelser" description="Salgs og handelsbetingelser" />
            <section>
                <article>

                    <h3>Salgs- og leveringsbetingelser for online bestillinger på www.zalando.dk og www.zircle.dk</h3>
                    <p>Herunder finder du vores generelle forretningsbetingelser, som danner grundlaget for tilvejebringelsen af alle tjenester på Zalando.dk.</p>
                    <p>Tilbuddene på vores websites www.zalando.dk og www.zircle.dk er udelukkende rettet mod forbrugere, der indgår et køb til et formål, der hverken kan henregnes til deres erhvervsmæssige eller arbejdsmæssige aktiviteter.</p>
                    <p>Zalando varer er alle de varer, som vi sælger på www.zalando.dk, medmindre vi oplyser, at varerne er Zalando partner varer.</p>
                    <p>Zalando partner varer er varer, som vi sælger på www.zalando.dk, og som er identificeret som Zalando partner varer. Alle Zalando-partnere er erhvervsdrivende.</p>
                    <p>Zalando Zircle varer er varer, som vi sælger på www.zalando.dk og www.zircle.dk og identificerer som "pre-owned".</p>
                </article>
                <article>
                    <h2>1. INDGÅELSE AF KØBSAFTALE OG LEVERING AF VARER</h2>
                    <p> <b>1.1</b> Med afgivelse af en bestilling erklærer du udelukkende at handle til private formål.</p>
                    <p> <b>1.2</b> Vi indgår udelukkende købsaftaler på dansk for så vidt angår de bestillinger, der foretages online på www.zalando.dk. Når du bestiller Zalando varer og Zalando Zircle varer , indgår du en købsaftale med Zalando SE, Valeska-Gert-Straße 5, 10243 Berlin, og når du bestiller Zalando partner varer, indgår du også købsaftale med den respektive Zalando partner. Zalando partnerne er specifikt identificeret under hver enkelt vares produktinformation.</p>
                    <p> <b>1.3</b> Ved at klikke ”Afsend bestillingen og betal”, afgiver du en bindende bestilling på varerne i din indkøbskurv. Vi sender dig en ordrebekræftelse pr. e-mail, så snart du har indsendt din bestilling. Der indgås en bindende købsaftale, når du modtager en ordrebekræftelse fra os. Ordrebekræftelsen anses for modtaget, så snart vi har afsendt den til den e-mail adresse, som du har registreret på din Zalando konto, og når denne e-mail er nået frem til serveren hos din e-mail udbyder. Vilkårene i købsaftalen vil blive gemt hos Zalando og vil være tilgængelige under ”Mit Zalando” på www.zalando.dk. Vær opmærksom på, at varer, der er bestilt via forudbetaling (reserveret betaling), vil blive ekspederet, så snart den fulde købspris samt eventuelle leveringsomkostninger er modtaget. Derfor anmoder vi dig om, at du overfører hele købsprisen for din bestilling, så snart du modtager din ordrebekræftelse, dog senest inden for 7 dage.</p>
                    <p> <b>1.4</b> Når du gennemfører dit køb, accepterer du, at kravet for betaling kan overdrages til tredjemand, herunder særligt men ikke begrænset til Zalando Payments GmBH. Du skal i den forbindelse være opmærksom på, at overdragelse kan ske til både selskaber i og udenfor Zalando-koncernen.</p>
                    <p> <b>1.5</b> Vi gør dig opmærksom på, at Zalando ikke er forpligtet til at levere din bestilling i tilfælde af, at vores leverandører undtagelsesvist ikke leverer til vores lager, uanset at vi har fulgt en korrekt bestillingspraksis (overensstemmende indkøbstransaktion). For at denne undtagelse finder anvendelse, er det en forudsætning, at vi ikke er juridisk ansvarlige for, at de omhandlede varer er utilgængelige, og vi skal desuden have underrettet dig om situationen uden ugrundet forsinkelse. Det er videre en forudsætning, at vi ikke har påtaget os indkøbsrisikoen i relation til den omhandlede bestilling. Hvis vi ikke kan skaffe din bestilling hjem, refunderer vi enhver betaling i relation hertil uden ugrundet forsinkelse.</p>
                    <p> <b>1.6</b> Vi påtager os ikke risikoen for at skulle skaffe bestillinger hjem andetsteds fra (indkøbsrisiko). Det gælder også for så vidt angår bestillinger af generiske varer (hvor det kun er varens type og funktion, der er beskrevet). Vi er udelukkende forpligtet til at foretage leveringen fra vores tilgængelige lager og fra det lager, hvorfra vi har bestilt fra vores leverandører. Vores lager omfatter den relevante Zalando partners lager i de tilfælde, hvor det er Zalando partner varer, der er bestilt. Vi leverer inden for Danmarks grænser. I de tilfælde hvor der er angivet tidsperioder i arbejdsdage, skal det forstås som alle dage mellem mandag og fredag (begge dage inklusiv), med undtagelse af offentlige fri- og helligdage i Danmark og i Tyskland.</p>
                    <p> <b>1.7</b> Når du vælger at kompensere for CO2-fodaftrykket i din bestilling på på siden med bestillingsoversigten, udgør dette en aftalemæssig bestanddel af din bestilling. Du vil blive informeret om bidragets størrelse før indgåelsen af aftalen på siden med bestillingsoversigten.</p>
                </article>
                <article>
                    <h2>2. PRISER, LEVERINGSOMKOSTNINGER OG EKSPRES LEVERING</h2>
                    <p> <b>2.1</b> Med afgivelse af en bestilling erklærer du udelukkende at handle til private formål.</p>
                    <p> <b>2.2</b> Vi indgår udelukkende købsaftaler på dansk for så vidt angår de bestillinger, der foretages online på www.zalando.dk. Når du bestiller Zalando varer og Zalando Zircle varer , indgår du en købsaftale med Zalando SE, Valeska-Gert-Straße 5, 10243 Berlin, og når du bestiller Zalando partner varer, indgår du også købsaftale med den respektive Zalando partner. Zalando partnerne er specifikt identificeret under hver enkelt vares produktinformation.</p>
                    <p> <b>2.3</b> Ved at klikke ”Afsend bestillingen og betal”, afgiver du en bindende bestilling på varerne i din indkøbskurv. Vi sender dig en ordrebekræftelse pr. e-mail, så snart du har indsendt din bestilling. Der indgås en bindende købsaftale, når du modtager en ordrebekræftelse fra os. Ordrebekræftelsen anses for modtaget, så snart vi har afsendt den til den e-mail adresse, som du har registreret på din Zalando konto, og når denne e-mail er nået frem til serveren hos din e-mail udbyder. Vilkårene i købsaftalen vil blive gemt hos Zalando og vil være tilgængelige under ”Mit Zalando” på www.zalando.dk. Vær opmærksom på, at varer, der er bestilt via forudbetaling (reserveret betaling), vil blive ekspederet, så snart den fulde købspris samt eventuelle leveringsomkostninger er modtaget. Derfor anmoder vi dig om, at du overfører hele købsprisen for din bestilling, så snart du modtager din ordrebekræftelse, dog senest inden for 7 dage.</p>
                    <p> <b>2.4</b> Når du gennemfører dit køb, accepterer du, at kravet for betaling kan overdrages til tredjemand, herunder særligt men ikke begrænset til Zalando Payments GmBH. Du skal i den forbindelse være opmærksom på, at overdragelse kan ske til både selskaber i og udenfor Zalando-koncernen.</p>
                    <p> <b>2.5</b> Vi gør dig opmærksom på, at Zalando ikke er forpligtet til at levere din bestilling i tilfælde af, at vores leverandører undtagelsesvist ikke leverer til vores lager, uanset at vi har fulgt en korrekt bestillingspraksis (overensstemmende indkøbstransaktion). For at denne undtagelse finder anvendelse, er det en forudsætning, at vi ikke er juridisk ansvarlige for, at de omhandlede varer er utilgængelige, og vi skal desuden have underrettet dig om situationen uden ugrundet forsinkelse. Det er videre en forudsætning, at vi ikke har påtaget os indkøbsrisikoen i relation til den omhandlede bestilling. Hvis vi ikke kan skaffe din bestilling hjem, refunderer vi enhver betaling i relation hertil uden ugrundet forsinkelse.</p>
                    <p> <b>2.6</b> Vi påtager os ikke risikoen for at skulle skaffe bestillinger hjem andetsteds fra (indkøbsrisiko). Det gælder også for så vidt angår bestillinger af generiske varer (hvor det kun er varens type og funktion, der er beskrevet). Vi er udelukkende forpligtet til at foretage leveringen fra vores tilgængelige lager og fra det lager, hvorfra vi har bestilt fra vores leverandører. Vores lager omfatter den relevante Zalando partners lager i de tilfælde, hvor det er Zalando partner varer, der er bestilt. Vi leverer inden for Danmarks grænser. I de tilfælde hvor der er angivet tidsperioder i arbejdsdage, skal det forstås som alle dage mellem mandag og fredag (begge dage inklusiv), med undtagelse af offentlige fri- og helligdage i Danmark og i Tyskland.</p>
                    <p> <b>2.7</b> Når du vælger at kompensere for CO2-fodaftrykket i din bestilling på på siden med bestillingsoversigten, udgør dette en aftalemæssig bestanddel af din bestilling. Du vil blive informeret om bidragets størrelse før indgåelsen af aftalen på siden med bestillingsoversigten.</p>
                </article>
                <article>
                    <h2>3. BETALING</h2>
                    <p> <b>3.1</b> Med afgivelse af en bestilling erklærer du udelukkende at handle til private formål.</p>
                    <p> <b>3.2</b> Vi indgår udelukkende købsaftaler på dansk for så vidt angår de bestillinger, der foretages online på www.zalando.dk. Når du bestiller Zalando varer og Zalando Zircle varer , indgår du en købsaftale med Zalando SE, Valeska-Gert-Straße 5, 10243 Berlin, og når du bestiller Zalando partner varer, indgår du også købsaftale med den respektive Zalando partner. Zalando partnerne er specifikt identificeret under hver enkelt vares produktinformation.</p>
                    <p> <b>3.3</b> Ved at klikke ”Afsend bestillingen og betal”, afgiver du en bindende bestilling på varerne i din indkøbskurv. Vi sender dig en ordrebekræftelse pr. e-mail, så snart du har indsendt din bestilling. Der indgås en bindende købsaftale, når du modtager en ordrebekræftelse fra os. Ordrebekræftelsen anses for modtaget, så snart vi har afsendt den til den e-mail adresse, som du har registreret på din Zalando konto, og når denne e-mail er nået frem til serveren hos din e-mail udbyder. Vilkårene i købsaftalen vil blive gemt hos Zalando og vil være tilgængelige under ”Mit Zalando” på www.zalando.dk. Vær opmærksom på, at varer, der er bestilt via forudbetaling (reserveret betaling), vil blive ekspederet, så snart den fulde købspris samt eventuelle leveringsomkostninger er modtaget. Derfor anmoder vi dig om, at du overfører hele købsprisen for din bestilling, så snart du modtager din ordrebekræftelse, dog senest inden for 7 dage.</p>
                </article>
            </section>
        </>
    )
}